using System.Reflection;

namespace Majorsilence.Forms.GdiDiff;

/// <summary>
/// Reflection-only API gap audit: upstream <c>System.Drawing.Common</c> vs. this repo's
/// <c>Majorsilence.Forms.Drawing</c> replacement (see <c>docs/gdi-gap-plan.md</c>).
///
/// Exists because the earlier hand-written audit in <c>COMPATIBILITY_MATRIX.md</c> was a type-level
/// source-listing comparison and went stale — this one is mechanical, member-level, and gated in CI so
/// the numbers cannot rot the same way.
///
/// Everything is loaded through <see cref="MetadataLoadContext"/>, so no target assembly is ever
/// executed and the fact that <c>System.Drawing.Common</c> only *runs* on Windows is irrelevant.
/// </summary>
internal static class Program
{
    private static int Main(string[] args)
    {
        var check = args.Contains("--check", StringComparer.Ordinal);
        var configuration = ArgValue(args, "--configuration") ?? "Release";
        var repoRoot = ArgValue(args, "--repo-root") ?? FindRepoRoot();
        if (repoRoot is null)
        {
            Console.Error.WriteLine("error: could not locate the repo root (no Majorsilence.Forms.slnx found above the current directory); pass --repo-root <dir>");
            return 2;
        }

        var baselinePath = ArgValue(args, "--baseline")
            ?? Path.Combine(repoRoot, "tools", "Majorsilence.Forms.GdiDiff", "baseline.txt");

        string[] gaps;
        try
        {
            gaps = GapScanner.Scan(repoRoot, configuration);
        }
        catch (FileNotFoundException ex)
        {
            Console.Error.WriteLine($"error: {ex.Message}");
            Console.Error.WriteLine($"hint: build the solution in {configuration} first (dotnet build --configuration {configuration}).");
            return 2;
        }

        if (!check)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(baselinePath)!);
            File.WriteAllLines(baselinePath, Header(configuration).Concat(gaps));
            Console.WriteLine($"wrote {gaps.Length} gap entries to {baselinePath}");
            return 0;
        }

        if (!File.Exists(baselinePath))
        {
            Console.Error.WriteLine($"error: no baseline at {baselinePath}; run without --check to create it.");
            return 2;
        }

        var baseline = File.ReadAllLines(baselinePath)
            .Where(l => l.Length > 0 && !l.StartsWith('#'))
            .ToHashSet(StringComparer.Ordinal);
        var current = gaps.ToHashSet(StringComparer.Ordinal);

        var added = current.Except(baseline, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();
        var closed = baseline.Except(current, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();

        foreach (var line in closed)
            Console.WriteLine($"  closed: {line}");

        if (added.Count > 0)
        {
            Console.Error.WriteLine($"\nGDI+ API gap set GREW by {added.Count} entr{(added.Count == 1 ? "y" : "ies")}:");
            foreach (var line in added)
                Console.Error.WriteLine($"  new gap: {line}");
            Console.Error.WriteLine("\nEither implement the missing surface, or regenerate the baseline deliberately:");
            Console.Error.WriteLine("  dotnet run --project tools/Majorsilence.Forms.GdiDiff");
            return 1;
        }

        Console.WriteLine(closed.Count > 0
            ? $"\nOK — no new gaps; {closed.Count} closed since the baseline. Regenerate it to lock the progress in."
            : "\nOK — no new gaps.");
        return 0;
    }

    private static IEnumerable<string> Header(string configuration) =>
    [
        "# GDI+ API gap baseline — generated by tools/Majorsilence.Forms.GdiDiff.",
        "# Regenerate: dotnet run --project tools/Majorsilence.Forms.GdiDiff",
        "# Verify:     dotnet run --project tools/Majorsilence.Forms.GdiDiff -- --check",
        $"# Compared against System.Drawing.Common (reflection-only) using the {configuration} build.",
        "# TYPE   <upstream full name>          = no equivalent type exists at all.",
        "# MEMBER <upstream type>.<member>      = the type exists but this member does not.",
        "# Entries here are gaps, not goals — see docs/gdi-gap-plan.md for what is deliberately out of scope.",
        "",
    ];

    private static string? ArgValue(string[] args, string name)
    {
        var i = Array.IndexOf(args, name);
        return i >= 0 && i + 1 < args.Length ? args[i + 1] : null;
    }

    private static string? FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "Majorsilence.Forms.slnx")))
                return dir.FullName;
            dir = dir.Parent;
        }
        return null;
    }
}
