using System.Reflection;

namespace Majorsilence.Forms.ApiDiff;

/// <summary>
/// Reflection-only API gap audit of the surfaces this repo reimplements: <c>System.Drawing.Common</c>
/// and <c>System.Windows.Forms</c> (see <c>docs/gdi-gap-plan.md</c> and
/// <c>docs/winforms-gap-plan.md</c>).
///
/// Exists because the hand-written audits in <c>COMPATIBILITY_MATRIX.md</c> were type-level, done by
/// eye, and went stale within a release. This one is mechanical, member-level, and gated in CI, so the
/// numbers cannot rot the same way.
///
/// Nothing is executed: every assembly is loaded through <see cref="System.Reflection.MetadataLoadContext"/>,
/// so it makes no difference that the upstream assemblies only <em>run</em> on Windows.
/// </summary>
internal static class Program
{
    private static int Main(string[] args)
    {
        if (args.Contains("--help", StringComparer.Ordinal) || args.Contains("-h", StringComparer.Ordinal))
        {
            PrintUsage();
            return 0;
        }

        var check = args.Contains("--check", StringComparer.Ordinal);
        var configuration = ArgValue(args, "--configuration") ?? "Release";
        var repoRoot = ArgValue(args, "--repo-root") ?? FindRepoRoot();
        if (repoRoot is null)
        {
            Console.Error.WriteLine("error: could not locate the repo root (no Majorsilence.Forms.slnx found above this assembly); pass --repo-root <dir>");
            return 2;
        }

        var requested = ArgValue(args, "--surface") ?? "all";
        var surfaces = requested.Equals("all", StringComparison.OrdinalIgnoreCase)
            ? Surface.All
            : Surface.All.Where(s => s.Name.Equals(requested, StringComparison.OrdinalIgnoreCase)).ToArray();

        if (surfaces.Length == 0)
        {
            Console.Error.WriteLine($"error: unknown surface '{requested}' (expected {string.Join("|", Surface.All.Select(s => s.Name))}|all)");
            return 2;
        }

        var failed = false;
        foreach (var surface in surfaces)
            failed |= Run(surface, repoRoot, configuration, check) != 0;

        return failed ? 1 : 0;
    }

    private static int Run(Surface surface, string repoRoot, string configuration, bool check)
    {
        string[] gaps;
        try
        {
            gaps = GapScanner.Scan(surface, repoRoot, configuration);
        }
        catch (FileNotFoundException ex)
        {
            Console.Error.WriteLine($"error [{surface.Name}]: {ex.Message}");
            Console.Error.WriteLine($"hint: build the solution in {configuration} first (dotnet build --configuration {configuration}).");
            return 2;
        }

        var baselinePath = surface.BaselinePath(repoRoot);

        if (!check)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(baselinePath)!);
            File.WriteAllLines(baselinePath, Header(surface, configuration).Concat(gaps));
            Console.WriteLine($"[{surface.Name}] wrote {gaps.Length} gap entries to {baselinePath}");
            return 0;
        }

        if (!File.Exists(baselinePath))
        {
            Console.Error.WriteLine($"error [{surface.Name}]: no baseline at {baselinePath}; run without --check to create it.");
            return 2;
        }

        var baseline = File.ReadAllLines(baselinePath)
            .Where(l => l.Length > 0 && !l.StartsWith('#'))
            .ToHashSet(StringComparer.Ordinal);
        var current = gaps.ToHashSet(StringComparer.Ordinal);

        var added = current.Except(baseline, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();
        var closed = baseline.Except(current, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();

        foreach (var line in closed)
            Console.WriteLine($"  [{surface.Name}] closed: {line}");

        if (added.Count > 0)
        {
            Console.Error.WriteLine($"\n[{surface.Name}] API gap set GREW by {added.Count} entr{(added.Count == 1 ? "y" : "ies")}:");
            foreach (var line in added)
                Console.Error.WriteLine($"  new gap: {line}");
            Console.Error.WriteLine("\nEither implement the missing surface, or regenerate the baseline deliberately:");
            Console.Error.WriteLine($"  dotnet run --project tools/Majorsilence.Forms.ApiDiff -- --surface {surface.Name}");
            return 1;
        }

        Console.WriteLine(closed.Count > 0
            ? $"[{surface.Name}] OK — no new gaps; {closed.Count} closed since the baseline. Regenerate it to lock the progress in."
            : $"[{surface.Name}] OK — no new gaps.");
        return 0;
    }

    private static IEnumerable<string> Header(Surface surface, string configuration) =>
    [
        $"# {surface.Name} API gap baseline — generated by tools/Majorsilence.Forms.ApiDiff.",
        $"# Regenerate: dotnet run --project tools/Majorsilence.Forms.ApiDiff -- --surface {surface.Name}",
        $"# Verify:     dotnet run --project tools/Majorsilence.Forms.ApiDiff -- --surface {surface.Name} --check",
        $"# Compared against {surface.UpstreamAssembly} (reflection-only) using the {configuration} build.",
        "# TYPE   <upstream full name>          = no equivalent type exists at all.",
        "# MEMBER <upstream type>.<member>      = the type exists but this member does not.",
        "# SIG    <upstream type>.<signature>   = the method exists but not with this overload's shape.",
        "# VALUE  <upstream type>.<member> ...  = the enum member exists but has a different number.",
        "#        A VALUE line is a bug, not a gap: designer/.resx code persists these as raw integers,",
        "#        so a wrong number corrupts data on round-trip instead of failing to compile.",
        "# Entries here are gaps, not goals — see the gap plan in docs/ for what is deliberately out of scope.",
        "",
    ];

    private static void PrintUsage() => Console.WriteLine(
        """
        api-diff — reflection-only API gap audit against the surfaces this repo reimplements

        USAGE
          dotnet run --project tools/Majorsilence.Forms.ApiDiff -- [options]

        OPTIONS
          --surface <name>      drawing | winforms | all (default: all)
          --check               Compare against the committed baseline and fail if the gap set grew.
                                Without it, the baseline is regenerated.
          --configuration <c>   Build configuration to read our assemblies from (default: Release).
          --repo-root <dir>     Repo root (default: found by walking up from this assembly).
          -h, --help            Show this help.

        Closing gaps never fails: --check only fails when the set GROWS. After closing some, rerun
        without --check to lock the progress into the baseline.
        """);

    private static string? ArgValue(string[] args, string name)
    {
        var i = Array.IndexOf(args, name);
        return i >= 0 && i + 1 < args.Length ? args[i + 1] : null;
    }

    private static string? FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "Majorsilence.Forms.slnx")))
                return dir.FullName;
            dir = dir.Parent;
        }
        return null;
    }
}
