using System;

namespace Majorsilence.Forms
{
    // Members collected from porting the Cyotek colour-picker controls. Same two causes as the Krypton
    // waves: a Form is not a Control here, so a form-derived class cannot reach Control's overridables;
    // and a few strip members were simply absent. Each is an override point a control library uses to
    // take part in behaviour it cannot otherwise observe.

    public partial class WindowBase
    {
        /// <summary>Raises the <see cref="FontChanged"/> event.</summary>
        /// <remarks>
        /// A form that lays itself out from its font -- scaling a dialog to the system font is the usual
        /// reason -- overrides this to re-measure. Declared here because a Form does not inherit
        /// <see cref="Control.OnFontChanged"/>; raised from the window's own Font setter.
        /// </remarks>
        protected virtual void OnFontChanged (EventArgs e) => FontChanged?.Invoke (this, e);

        /// <summary>Raised when the window's font changes.</summary>
        /// <inheritdoc cref="OnFontChanged"/>
        public event EventHandler? FontChanged;
    }

    public abstract partial class ToolStripDropDownItem
    {
        /// <summary>Creates the drop-down this item shows.</summary>
        /// <remarks>
        /// The substitution point for a custom drop-down: an item that hosts a control (a colour picker,
        /// a calendar) overrides this to return its own <see cref="ToolStripDropDown"/> rather than the
        /// default menu. Called on first access to <see cref="DropDown"/>, so an override is what the
        /// item ends up owning.
        /// </remarks>
        protected virtual ToolStripDropDown CreateDefaultDropDown ()
            => new ToolStripDropDown { OwnerItem = this, IsAutoGenerated = true };
    }

    public partial class ToolStripSplitButton
    {
        /// <summary>Raises the <see cref="ButtonClick"/> event.</summary>
        /// <remarks>
        /// A split button has two halves: clicking the button part performs the default action, clicking
        /// the arrow opens the drop-down. This is the button half, which is why it is separate from
        /// <c>Click</c> -- a derived split button overrides it to apply the currently-selected value
        /// without opening anything.
        /// </remarks>
        protected virtual void OnButtonClick (EventArgs e) => ButtonClick?.Invoke (this, e);
    }

    public partial class ToolStripItem : IDisposable
    {
        /// <summary>Releases the resources used by the item.</summary>
        /// <remarks>
        /// The disposable half of the item contract. A strip item that owns something -- a hosted
        /// control, a drop-down it built, an image it loaded -- overrides this to release it, so its
        /// absence meant such an item leaked whatever it held with no way to say otherwise.
        /// </remarks>
        protected virtual void Dispose (bool disposing) { }

        /// <summary>Releases the resources used by the item.</summary>
        public void Dispose ()
        {
            Dispose (true);
            GC.SuppressFinalize (this);
        }

        /// <summary>Gets the list this item's event handlers are stored in.</summary>
        /// <remarks>
        /// WinForms puts this on <c>Component</c>, and a control library that declares many rarely-used
        /// events uses it to avoid a delegate field per event -- the `Events.AddHandler(s_key, value)`
        /// idiom this library already uses inside Control. Exposed here so a derived strip item can
        /// declare its own events the same way.
        /// </remarks>
        protected System.ComponentModel.EventHandlerList Events => events ??= new System.ComponentModel.EventHandlerList ();

        private System.ComponentModel.EventHandlerList? events;
    }
}
